name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

      - name: Disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update

      - name: Install tools & libraries (Ubuntu)
        run: |
          sudo apt update
          sudo apt install python3 python3-pytest acpica-tools cmake g++-multilib
          # https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917
          sudo sysctl vm.mmap_rnd_bits=28

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests (64-bit)
        run: python3 ${{ github.workspace }}/tests/run_tests.py --bitness=64

      - name: Run tests (32-bit)
        run: python3 ${{ github.workspace }}/tests/run_tests.py --bitness=32

